{"name": "test_twice_deleted_user_030", "status": "passed", "description": "\n    Удалить удаленного пользователя\n\n    Ожидаемый результат:\n        Статус-код 404;\n        Время ответа сервера - не превышает 500ms;\n        Response header \"Content-Type\": \"application/json\"\n        Response header \"Connection\": \"keep-alive\"\n        В тексте ошибки указан отправленный нами \"user_id\"\n    ", "start": 1721415264964, "stop": 1721415265095, "uuid": "dea9bcf2-65c2-4c54-974b-44c78fcf8fda", "historyId": "78799c8ef7794fa04b3c68aae376a196", "testCaseId": "78799c8ef7794fa04b3c68aae376a196", "fullName": "tests.users.test_users#test_twice_deleted_user_030", "labels": [{"name": "tag", "value": "users"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-55MLA3F"}, {"name": "thread", "value": "23412-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}